### PR TITLE
Fixes for handling ObjectiveFunctionType

### LINKED ISSUE #242: Fix ObjectiveFunction in ListOfAttributesSet
This line should be the appropriate `ObjectiveFunction{T}` instead of just `ScalarAffineFunction`.

https://github.com/JuliaOpt/Gurobi.jl/blob/db91e1e9fabc3f62f30265780e6a577016ebba4e/src/MOI_wrapper.jl#L305

### LINKED ISSUE #244: Setting FEASIBILITY_SENSE should remove objective
We need to zero the objective when the user sets `FEASIBILITY_SENSE`:
https://github.com/JuliaOpt/Gurobi.jl/blob/4ff0d037a614ad3dcbcdf34de2cc6ef5d4eb1401/src/MOI_wrapper.jl#L519-L521

We probably also need to change `ObjectiveFunctionType` to throw an error if `FEASIBILITY_SENSE`.

### PR DESCRIPTION
**Pull request by odow**
Closes #244
Closes #242

### CODE REVIEW

File: test/MOI_wrapper.jl [hunk 1]
```diff
@@ -921,3 +921,29 @@ end
...
     @test MOI.get(model, MOI.ConstraintDual(), xu) == 0.0
 end
+
+@testset "Objective functions" begin
+    model = Gurobi.Optimizer(GUROBI_ENV)
+    x = MOI.add_variable(model)
+    @test MOI.get(model, MOI.ObjectiveSense()) == MOI.FEASIBILITY_SENSE
+    @test MOI.get(model, MOI.ListOfModelAttributesSet()) == Any[MOI.ObjectiveSense()]
+    MOI.set(model, MOI.ObjectiveSense(), MOI.MIN_SENSE)
+    MOI.set(model, MOI.ObjectiveFunction{MOI.SingleVariable}(), MOI.SingleVariable(x))
```
Comment (blegat) [inline test/MOI_wrapper.jl]: Support for `SingleVariable` should be dropped now that we have `Bridge.Objective.FunctionizeBridge`

Comment (odow) [reply test/MOI_wrapper.jl]: Agreed. But that can wait for a different PR.
