### PR TITLE
Escape GUROBI_HOME path on windows

### LINKED ISSUE #118: error compiling getlibversion
On **Windows_7_x64** installed **julia-0.6.2-win64.exe**

File **gurobi75.dll** in **D:\Julia\Solvers\bin**

```
julia> ENV["GUROBI_HOME"]
"D:\\Julia\\Solvers"

julia> Pkg.add("Gurobi")
INFO: Installing Gurobi v0.3.3
INFO: Building Gurobi
INFO: Package database updated

julia> include("C:\\Users\\User\\.julia\\v0.6\\Gurobi\\test\\mip_01.jl")
INFO: Precompiling module Gurobi.
ERROR: LoadError: LoadError: error compiling getlibversion: could not load libra
ry "D:JuliaSolveringurobi75.dll"
The specified module could not be found.

Stacktrace:
 [1] include_from_node1(::String) at .\loading.jl:576
 [2] include(::String) at .\sysimg.jl:14
 [3] include_from_node1(::String) at .\loading.jl:576
 [4] include(::String) at .\sysimg.jl:14
 [5] anonymous at .\<missing>:2
while loading C:\Users\User\.julia\v0.6\Gurobi\src\grb_common.jl, in expression
starting on line 72
while loading C:\Users\User\.julia\v0.6\Gurobi\src\Gurobi.jl, in expression star
ting on line 66
ERROR: LoadError: Failed to precompile Gurobi to C:\Users\User\.julia\lib\v0.6\G
urobi.ji.
Stacktrace:
 [1] compilecache(::String) at .\loading.jl:710
 [2] _require(::Symbol) at .\loading.jl:497
 [3] require(::Symbol) at .\loading.jl:405
 [4] include_from_node1(::String) at .\loading.jl:576
 [5] include(::String) at .\sysimg.jl:14
while loading C:\Users\User\.julia\v0.6\Gurobi\test\mip_01.jl, in expression sta
rting on line 13
```

### PR DESCRIPTION
**Pull request by odow**
Closes #118

### CODE REVIEW

File: deps/build.jl [hunk 1]
```diff
@@ -24,7 +24,12 @@ for a in aliases
             push!(paths_to_try, joinpath(ENV["GUROBI_HOME"], "lib", string("lib", a, ".so")))
         end
         if Compat.Sys.iswindows()
-            push!(paths_to_try, joinpath(ENV["GUROBI_HOME"], "bin", string(a, ".", Libdl.dlext)))
+            path = joinpath(ENV["GUROBI_HOME"], "bin", string(a, ".", Libdl.dlext))
+            # When this path gets written out to a file, it will escape the
```
Comment (blegat) [inline deps/build.jl]: If this is for writting it to file then shouldn't this be in `write_depsfile`?

Comment (blegat) [reply deps/build.jl]: Otherwise it also affects the path given to `dlopen_e`

File: deps/build.jl [hunk 2]
```diff
@@ -1,24 +1,35 @@
...
 end
 
 function write_depsfile(path)
-    f = open(depsfile,"w")
-    println(f,"const libgurobi = \"$path\"")
-    close(f)
+    # When `path` gets written out to a file, it will escape any backslashes, so
+    # we need to doubly escape them. If your path uses forward slashes, this
+    # operation won't do anything.
+    path = replace(path, "\\" => "\\\\")
```
Comment (blegat) [inline deps/build.jl]: What happens if there are backslashes in a unix path (i.e. the backslashes are part of the name of a folder and do not represent a separation), should we make the replace or not ? That is, should we do this on Windows only ?
